[package]
name = "teleswap"
version = "0.0.1"
edition = "2024"
published-at = "0x2678c2594a48bb3c35fd205fb42f7205b1479825567167f0cb5e5d3e7edd845a"

[dependencies]
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/cetus_clmm", rev = "testnet-v1.26.0", override = true }
BridgedUSDC = { local = "../mock/mock_coins/usdc" }
BridgedUSDT = { local = "../mock/mock_coins/usdt" }
BridgedBTC = { local = "../mock/mock_coins/btc" }
btcrelay = { local = "../mock/mock_btcrelay" }


[addresses]
teleswap = "0x0"
