[package]
name = "teleswap"
version = "0.0.1"
edition = "2024"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
btcrelay = { local = "../btcrelay-package" }

[addresses]
teleswap = "0x0"
btcrelay = "0x0"
sui = "0x2" 