[package]
name = "teleswap"
version = "0.0.1"
edition = "2024"

[dependencies]
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/cetus_clmm", rev = "mainnet-v1.51.0" }

BridgedUSDC = { git = "https://github.com/MystenLabs/sui.git", subdir = "bridge/move/tokens/usdc", rev = "main" }
BridgedUSDT = { git = "https://github.com/MystenLabs/sui.git", subdir = "bridge/move/tokens/usdt", rev = "main" }
BridgedBTC  = { git = "https://github.com/MystenLabs/sui.git", subdir = "bridge/move/tokens/btc", rev = "main" }
btcrelay = { local = "../btcrelay-package" }


[addresses]
teleswap = "0x0"
sui = "0x2"

