[package]
name = "teleswap"
version = "0.0.1"
edition = "2024"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", rev = "e54b798790ed", subdir = "crates/sui-framework/packages/move-stdlib", override = true }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "e54b798790ed", override = true }

CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/cetus_clmm", rev = "testnet-v1.25.0" }

usdc = { git = "https://github.com/circlefin/stablecoin-sui.git", subdir = "packages/usdc", rev = "master" }
BridgedUSDT = { git = "https://github.com/MystenLabs/sui.git", subdir = "bridge/move/tokens/usdt", rev = "main" }
BridgedBTC = { git = "https://github.com/MystenLabs/sui.git", subdir = "bridge/move/tokens/btc", rev = "main" }
btcrelay = { local = "../btcrelay-package" }


[addresses]
teleswap = "0x0"
sui = "0x2"

